name: 'Arwest inc Giphy for comment'
description: 'Add a Giphy GIF comment to new pull request'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true
runs:
  using: 'node21'
  main: 'dist/index.js'

branding:
  icon: 'award'
  color: 'green'